version: '3.5'
services:
  traefik:
    image: traefik:v2.9
    command:
      {% if DEBUG == True %}
      - "--api.insecure=true"
      {% endif %}
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--serverstransport.insecureskipverify=true"
      - "--certificatesresolvers.tesla-tlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.tesla-tlschallenge.acme.email={{ TESLA_ADMIN_MAIL }}"
      - "--certificatesresolvers.tesla-tlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.tesla-tlschallenge.acme.httpchallenge.entrypoint=http"
      - "--providers.docker.network=tesla_public"
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    ports:
      {% if DEBUG == True %}
      - "8080:8080"
      {% endif %}
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks:
      - tesla_public
      - tesla_private
volumes:
  traefik_data:
    driver_opts:
      type: none
      device: {{ DEPLOYMENT_DATA_PATH }}/traefik
      o: bind

networks:
  tesla_public:
    external: true
  tesla_private:
    external: true
